# Generated by Django 3.2.3 on 2021-05-21 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='serie_unico',
            new_name='serieunico',
        ),
    ]
